services:
  postgres:
    image: postgres:17
    container_name: recipes-catalog_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1512BDS7425
      POSTGRES_DB: RecipesCatalogBD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
#    image: redis:7
#    container_name: recipes-catalog_redis
#    restart: always
#    ports:
#      - "6379:6379"
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: recipes-catalog
#    restart: always
#    depends_on:
#      - postgres
#      - redis
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RecipesCatalogBD
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1512BDS7425
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#
#volumes:
#  postgres_data: